name: Frontend CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    # Checks out the repository code to the runner

    - name: Set Up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    # Sets up Python 3.9 environment

    - name: Install Dependencies
      run: |
        cd frontend
        pip install -r requirements.txt
    # Installs Python dependencies from the requirements.txt file

    - name: Verify pytest Installation
      run: |
        cd frontend
        pip show pytest
    # Verifies that pytest is installed

    - name: List Installed Packages
      run: |
        cd frontend
        pip freeze
     # Lists installed packages to verify that all dependencies are installed

    - name: Run Tests
      run: |
        cd frontend
        pytest
    # Runs the test suite using pytest

    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v2
    # Sets up Docker Buildx to support multi-platform builds

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    # Logs in to Docker Hub using the Docker credentials 

    - name: Build and Push Docker Image
      run: |
        cd frontend
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest --push .
       # Builds the Docker image and pushes it to Docker Hub
